theme: minima
title: Nasri Anis Blog
description: "Tech, Cybersecurity, Networking, Coding ect"
future: true


github_username: "annisvvv"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md