theme: minima
title: Nasri Anis Blog
logo: "/assets/profile.jpg"
description: "Email: nasrianis213@gmail.com"
future: true


github_username: "annisvvv"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md